org.gradle.daemon=false
org.gradle.debug=false
# NeoForge and Minecraft version do not matter, only required for building, unless you plan to use Data Generators.
minecraft_version=1.21.1
neo_version=21.1.251

# Mod Info (mods.toml, neoforge.toml, fabric.mod.json, quilt.mod.json)
mod_license=All Rights Reserved
mod_id=trialglow
# not required, but recommended
mod_group_id=com.boterbramkroket.trialglow
mod_version=1.0.0
mod_name=Trial Glow
mod_authors=BoterBramKroket
# Replace [MOD SLUG] with the slug of your mod on CurseForge
mod_display_url = https://www.curseforge.com/minecraft/mc-mods/[MOD SLUG]
# Replace [MOD SLUG] with the slug of your mod on Modrinth
#mod_display_url = https://modrinth.com/datapack/[MOD SLUG]
# Replace [MODRINTH_ID] with the ID of your mod on Modrinth
mod_update_url=https://api.modrinth.com/updates/[MODRINTH_ID]
mod_description=Ring a bell on top of a trial spawner to highlight its mobs

# Minecraft pack.mcmeta: https://minecraft.wiki/w/Pack_format
pack_format=48
pack_format_min=48
pack_format_max=121
# Color Codes (use escaped MOTD codes): https://minecraft.fandom.com/wiki/Formatting_codes#Use_in_server.properties_and_pack.mcmeta
mod_description_short=Ring a bell on top of a trial spawner to highlight its mobs