# ...
org.gradle.daemon=false

# Minecraft & NeoForge version (Required for building)
minecraft_version=1.21.1
neo_version=21.1.251

# Mod Info (mods.toml, neoforge.toml, fabric.mod.json, quilt.mod.json)
mod_license=MIT
mod_id=trialglow
mod_group_id=com.boterbramkroket.trialglow
mod_version=1.0.0
mod_name=Trial Glow
mod_authors=BoterBramKroket
mod_display_url=https://modrinth.com/datapack/trialglow
# TODO Add Display URL
mod_update_url=https://api.modrinth.com/updates/[MODRINTH_ID]
mod_description=Ring a bell on top of a trial spawner to highlight its mobs

# Minecraft pack.mcmeta
pack_format=48
pack_format_min=48
pack_format_max=121
# TODO Add Color Codes
mod_description_short=Ring a bell on top of a trial spawner to highlight its mobs