modLoader = 'lowcodefml'
loaderVersion = "[0,)"
license = "MIT"
showAsResourcePack = false
issueTrackerURL = "https://github.com/BoterBramKroket/trialglow/issues"

[[mods]]
modId = "trialglow"
version = "1.0.0"
displayName = "Trial Glow"
logoFile = "pack.png"
iconFile = "pack.png"
authors = "BoterBramKroket"
displayURL = "https://modrinth.com/datapack/trialglow"
updateJSONURL = "https://api.modrinth.com/updates/p09B6ESi/forge_updates.json"
description = '''Ring a bell on top of a trial spawner to highlight its mobs'''